### ISSUE TITLE
Please write down all the icons' name

### ISSUE THREAD

**Issue by Yellowweii** [chouhan-rahul/icons_plus#10]
When I used  icons_plus,  I really didn't  konw the name of these icons. Therefore,  I couldn't use them correctly. Dear author,  if you look through this message, hope you can list all the icons' name,  that  will be a nice thing.

**Comment by chouhan-rahul** [comment]
Firstly You have to import icons_plus package like this import 'package:icons_plus/icons_plus.dart';

**Comment by chouhan-rahul** [comment]
To initiate the process, please ensure you import the icons_plus package using the following statement:

import 'package:icons_plus/icons_plus.dart';

Following the import, you gain access to a diverse range of icons within the icons_plus package. For instance, if you wish to utilize a Bootstrap icon, you can do so by employing the syntax:

Icon(Bootstrap.google)

Similarly, for FontAwesome icons, the syntax is:

Icon(FontAwesome.google)
