### ISSUE TITLE
There is a Trojan in this repo. 

### ISSUE THREAD

**Issue by 3kdeveloper** [chouhan-rahul/icons_plus#3]
![image](https://user-images.githubusercontent.com/77343380/188100199-30340cdb-de42-451c-a710-4598f8b79f76.png)
![image](https://user-images.githubusercontent.com/77343380/188100317-b6477ceb-3881-4f5d-9b94-a8e4f8e66208.png)

**Comment by imRahulChouhan** [comment]
Hi, I checked, but there were no viruses. Don't worry, a new version will be released tomorrow.
