### ISSUE TITLE
Solid & Outline Icons

### ISSUE THREAD

**Issue by obed-king** [chouhan-rahul/icons_plus#8]
I discovered your package today and must say, it is great. The only issue I encounter is when I want to use a solid version of Font Awesome, I don't kinda know how to do that. I don't know if it is an option already, and I fail to figure it out. Having the option for font outlines for IonIcons too.

**Comment by chouhan-rahul** [comment]
All issues will be resolved by December 15, 2023, as I will be releasing icons_plus 5, which includes additional icon sets and comprehensive documentation.
